language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
  - scala: 2.12.1
    jdk: openjdk6
  - scala: 2.12.1
    jdk: openjdk7
  - scala: 2.12.1
    jdk: oraclejdk7

script:
  - sbt clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION "test"
  - sbt ++$TRAVIS_SCALA_VERSION "+scalaJsonASTJVM/mimaReportBinaryIssues"

after_success:
  - bash <(curl -s https://codecov.io/bash)
