language: scala

scala:
  - 2.10.6
  - 2.12.1
  - 2.11.8
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
  - scala: 2.12.1
    jdk: openjdk6
  - scala: 2.12.1
    jdk: openjdk7
  - scala: 2.12.1
    jdk: oraclejdk7
