language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
jdk:
  - oraclejdk7
env: RUN_MIMA=false
matrix:
  include:
  - scala: 2.12.1
    jdk: oraclejdk8
    env: RUN_MIMA=true

script:
  - sbt clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION "test"
  - if [ "RUN_MIMA" == "true" ]; sbt ++$TRAVIS_SCALA_VERSION "+scalaJsonASTJVM/mimaReportBinaryIssues" ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
